### ISSUE TITLE
Logger null check in DgcItalianRulesValidator

### ISSUE THREAD

**Issue by FrancescoBonizzi** [DevTrevi/DgcReader#18]
Hi and thanks a lot for you work!

I think I found a little issue here:
![image](https://user-images.githubusercontent.com/11348479/145427070-c2ce5927-a9c6-4f32-b6a6-8f68d2f65faf.png)

Maybe in the `Strict2G` if, the `_logger` should be guarded with `?`.

I'm very sorry but at the moment I don't have time to make a pull request!

**Comment by DevTrevi** [comment]
Hi @FrancescoBonizzi, you are right, I forgot to check nullability in that line.
I will add the missing null conditional operator in the upcoming release, thanks for reporting it 👍
