### ISSUE TITLE
PARTIALLY_VALID status has been deprecated

### ISSUE THREAD

**Issue by astagi** [DevTrevi/DgcReader#26]
Reference: https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/pull/85

**Comment by DevTrevi** [comment]
Buonasera @astagi , ti ringrazio per la segnalazione. Questa modifica deve avere effetto immediato oppure dovrà essere implementata per la prossima release dell'SDK ( > 1.0.4 )?

Ho visto che sono state aperte delle issue a tutti i manutentori delle librerie di validazione certificate per avvisarli di questa modifica.
Per quanto mi riguarda, credo che questa modalità di segnalazione sia molto comoda e ci consenta di non "dimenticare" di riportare le modifiche principali alle librerie.
Posso aspettarmi che anche le prossime variazioni verranno segnalate in questo modo? (ad esempio la nuova verifica della blacklist)? 
Se questa modalità venisse consolidata sarei molto favorevole

**Comment by astagi** [comment]
Buonasera @DevTrevi perdona il ritardo con il quale rispondo. Vedo che la modifica è stata effettuata, possiamo chiudere la issue? 

Pensavo di intervenire personalmente per avvertire tutti gli autori degli SDK dei cambiamenti, ma stiamo valutando anche altre idee per centralizzare il tutto, come mettere un CHANGELOG su [repo di onboarding](https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding) in modo da comunicare i cambiamenti a tutti quelli che watchano.

**Comment by DevTrevi** [comment]
Buongiorno @astagi , ho implementato la modifica ma non ho ancora rilasciato la nuova versione che la contiene, dovrei farlo a breve includendo anche la nuova gestione della blacklist per allineare la libreria all'SDK 1.1.0

Anche l'idea di un changelog non sarebbe male, l'ideale sarebbe avere un elenco delle specifiche di alto livello che descrivano le modifiche concettuali richieste per la versione successiva dell'sdk.

Attualmente per riportare le nuove features dell'sdk ufficiale è necessario analizzare il codice confrontandolo con quello della versione precedente, ed essendo i vari sdk indipendenti organizzati diversamente a livello di codice, diventa facile saltare o male interpretare qualche funzionalità.

Se fosse possibile, sarebbe utile avere una descrizione di ciascuna feature prevista per la successiva versione dell'sdk **prima** del suo rilascio, in modo da poter allineare gli sdk indipendenti in parallelo a quello ufficiale.
Un'idea potrebbe essere l'utilizzo di _issues_ raggruppate in _milestones_ tracciate all'interno del repository dell'sdk ufficiale, ciascuna delle quali descriva le specifiche e il contesto di utilizzo delle nuove features che verranno implementate

Es:

- Milestone 1.1.0
  - Issue: deprecato PARTIALLY_VALID (descrizione...)
  - Issue: nuova gestione blacklist (descrizione, contesto...)
- Milestone 1.2.0
  - Issue: nuova feature....

Magari più tardi aprirò una issue sul repo di onboarding per discuterne anche con gli altri sviuppatori e vedere se ci sono altri suggerimenti a riguardo

**Comment by astagi** [comment]
Mi sembra un'ottima idea @DevTrevi ! La parte project / milestone di GitHub può essere sfruttata per tale scopo. Io intanto ho aperto una PR per il changelog possiamo tranquillamente sfruttare entrambe le parti
