### ISSUE TITLE
Problems with Mono

### ISSUE THREAD

**Issue by bortolin** [DevTrevi/DgcReader#27]
Ciao, intanto grazie per aver sviluppato questa libreria molto utile. 

Ho fatto dei test e pur supportando .NET Standard 2.0, purtroppo però ha dei problemi con la gestione dei certificati quanto utilizzata in ambiate Mono (Es. Xamarin). 

Credo dipenda dal fatto che System.Security.Cryptography.X509Certificates in Mono non implementa tutte le funzionalità o non si comporta ugualmente,  mentre sembra funzionare benissimo con Bouncy Castle.

Probabilmente utilizzando solamente Bouncy Castle anche per il .Net Standard si potrebbe rendere compatibile anche per per Mono.

**Comment by DevTrevi** [comment]
Ciao @bortolin , ti ringrazio per avermelo segnalato, purtroppo non ho ancora avuto tempo di fare una prova su Xamarin, lo farò appena possibile.
Nel frattempo potresti darmi qualche dettaglio aggiuntivo riguardo l'errore (quale funzione va in errore, i dettagli dell'eccezione, dettagli sulla versione di Xamarin)?

**Comment by andrekiba** [comment]
ciao @DevTrevi hai per caso avuto modo di verificare questa issue con Xamarin. Vorrei provare nei prossimi giorni e nel caso posso dare una mano a capire il motivo. Grazie.

**Comment by DevTrevi** [comment]
CIao @andrekiba , sono riuscito giusto a verificare, il problema come diceva @bortolin è che parecchie funzionalità del namespace System.Security.Cryptography non sono implementate in xamarin.android o xamarin.ios...

Putroppo non ho ancora avuto tempo di sistemarlo, stavo pensando di aggiungere target di compilazione specifici per Xamarin, oppure più semplicemente di spostare i target in questo modo:
- .netstandard (include xamarin), net452: BouncyCastle
- net47, net5.0: System.Security.Cryptography
In questo modo, le versioni obsolete del framework e xamarin/mono utilizzeranno BouncyCastle, mentre le versioni più recenti di .NET framework e quelle supportate di .NET continueranno a usare le api "native".

Mi servirà ancora qualche giorno per poterci mettere mano, vi avviserò qui quando sarà pronto un aggiornamento

**Comment by bortolin** [comment]
In effetti avevo provato anche io a fare la stessa tentando di forzare BouncyCastle, perché in effetti l'implentazione di System.Security.Cryptography per Xamarin (Mono) non implementa "Elliptic Curve Digital Signature Algorithm".

Inoltre ho notato che quando viene scaricato il certificato non lo riesce a caricare come certificato  X509Certificate2 se prima non lo tratto come stringa Base64 e lo converto in array nel metodo FetchCertificate in ItalianTrustListProvider.cs


  ```
var response = await _httpClient.SendAsync(request, cancellationToken);
  if (response.IsSuccessStatusCode)
  {
          //var content = await response.Content.ReadAsByteArrayAsync();
        
          var content = Convert.FromBase64String(await response.Content.ReadAsStringAsync());
  
  int? newToken = null;
  if (response.Headers.TryGetValues(HeaderResumeToken, out var newTokens))

```

**Comment by DevTrevi** [comment]
Ciao a tutti, ho rilasciato la versione 2.2.0 che dovrebbe risolvere i problemi di compatibilità con Xamarin.
Per il salvataggio dei dati, vi consiglio di utilizzare `FileSystem.CacheDirectory` come percorso base per tutti i provider, quello di default (`Directory.GetCurrentDirectory()`) non è accessibile

**Comment by andrekiba** [comment]
ciao @DevTrevi grazie per l'aggiornamento
