### ISSUE TITLE
Check SuperGreenPass for over 50 in Italy

### ISSUE THREAD

**Issue by simoneluconi** [DevTrevi/DgcReader#42]
I don't know if what i am asking is correct, but with the new rules in Italy from the 15 February 2022 to the 15 June 2022 as reported from [ilsole24ore](https://www.ilsole24ore.com/art/dall-obbligo-vaccinale-gli-over-50-super-green-pass-il-lavoro-ecco-calendario-nuovi-obblighi-AEGZfn6?refresh_ce=1):

> Obbligo di Green Pass rafforzato per tutti i lavoratori (pubblici e privati) e i liberi professionisti di almeno 50 anni. Chi non è ancora vaccinato dovrà effettuare la prima dose del vaccino entro il 31 gennaio per ottenere un Green Pass rafforzato valido a partire dal 15 febbraio (il certificato verde è rilasciato subito dopo la prima dose ma è attivato il quindicesimo giorno successivo alla somministrazione)

So from the 15th i need to check if the person is above 50 and then i need to validate the certificate with `ValidationMode.Basic3G`, if not so i need to validate it with `ValidationMode.Strict2G`. 

It's possible to implement a new `DgcItalianRulesValidatorOptions` or check it direcly into the code for this case? 

Because right now if i understand correctly i would need to call first `DgcReaderService` with no argument only to decode the DGC and check the `DateOfBirth`, then call `DgcReaderService` with the correct `ValidationMode`.

**Comment by DevTrevi** [comment]
Hi @simoneluconi , these new rules are not implemented yet by the library, but as soon as these new rules will be implementd by the [official sdk](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android), I will align the library too.
I guess this will happen in the next few weeks, before the deadline of February 15th.

Meanwhile, if you want you can simulate the new behavior as you described, forcing the 2G validation after reading the birth date on the pass (you can do it by calling the `Decode` function)

**Comment by energywave** [comment]
I think that the correct handling of this is to enforce this rule in the DgcItalianRulesValidator, by checking the current date if it's beyond the 15th february then if the user age (calculated from the birth date in the DGC) is 50 or more then requires the vaccination or the recovery as per official rules.
Thus not creating one more ValidationMode enum, in my opinion.
That said it's totally doable a workaround even now. Validate the DGC with the Basic2G (because if the zone requires a Basic3G validation there is no problem...) then, if validation is successful, access the DGC object, calculate the age and, if the age is >=50 then check if there is a vaccination or recovery entry, otherwise fail the validation on the client.
Yes, it's better to implement this in the library of course :)

**Comment by bortolin** [comment]
As you can read from this issue from the official SDK, they are already working on it [https://github.com/ministero-salute/it-dgc-documentation/issues/10](https://github.com/ministero-salute/it-dgc-documentation/issues/10)

**Comment by andrekiba** [comment]
ciao @DevTrevi, we have to support different scan mode (as the official app does). But it's not clear for me how I can achieve this with just one instance of the DgcService registered in the DI container. I would expect something that would allow to pass the scan mode (3G, 2G...) to the Verify method for example, no? I see that I can add more validators (this is a validator parameter correct?) but then how I can choose which one to use based on a selection that comes from the user?
Thank you I suppose I missed something :-)

**Comment by DevTrevi** [comment]
> ciao @DevTrevi, we have to support different scan mode (as the official app does). But it's not clear for me how I can achieve this with just one instance of the DgcService registered in the DI container. I would expect something that would allow to pass the scan mode (3G, 2G...) to the Verify method for example, no? I see that I can add more validators (this is a validator parameter correct?) but then how I can choose which one to use based on a selection that comes from the user? Thank you I suppose I missed something :-)

Hi @andrekiba , if you need to specify the validation mode for each request, you can use the `VerifyForItaly` extension method instead of `Verify`.
This method uses always "IT" as acceptance country, allowing to specify the validation mode for each request

**Comment by andrekiba** [comment]
Hi @DevTrevi, yes sorry found it yesterday evening but I forgot to update here!

**Comment by DevTrevi** [comment]
HI everyone, I just released version 2.5.0 that includes all the features of the official sdk version 1.1.5, released few hours ago, including WORK mode for checking greenpass for over 50

**Comment by simoneluconi** [comment]
I think we should consider this issue as closed right?
