### ISSUE TITLE
Problemi con Blacklist

### ISSUE THREAD

**Issue by sfracell** [DevTrevi/DgcReader#43]
Ciao, innanzitutto grazie per la disponibilità e per il lavoro fatto.
Ho un problema che non riconosce i certificati annullati me li ritrovo sempre validi e mi riporta blacklistcheck: not blacklisted, la decodifica avviene correttamente, ho provato sia con framework 4.7, core 3.1 e .net 6 sia su windows 10 che windows 11, la stessa cosa se utilizzo Verify o VerifyforItaly, se utilizzo ItalianDrlBlacklistProvider mi riporta status: needsruleverification.
Cortesemente riesci a dirmi dove sbaglio?

       private void VerGreenPass(string code)
       {   
            ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;
            var httpClient = new HttpClient();            

            var trustListProvider = ItalianTrustListProvider.Create(httpClient, new ItalianTrustListProviderOptions
            {
                RefreshInterval = TimeSpan.FromHours(24),
                MinRefreshInterval = TimeSpan.FromHours(1),
                SaveCertificate = true,
            });
         
            var rulesValidator = DgcItalianRulesValidator.Create(httpClient,
                new DgcItalianRulesValidatorOptions
                {
                    RefreshInterval = TimeSpan.FromHours(24),
                    MinRefreshInterval = TimeSpan.FromHours(1),
                    ValidationMode = ValidationMode.Strict2G
                    
                });
            
            //var blacklistProvider = ItalianDrlBlacklistProvider.Create(httpClient,

                //new ItalianDrlBlacklistProviderOptions
                //{
                //   RefreshInterval = TimeSpan.FromHours(24),
                //    MinRefreshInterval = TimeSpan.FromHours(1)                
                //});           
       
            var dgcReader = DgcReaderService.Create(trustListProvider, rulesValidator, rulesValidator, null);

           
            var result = dgcReader.GetValidationResult(code, "IT");

         }

**Comment by DevTrevi** [comment]
Ciao @sfracell ,

dal codice che hai incluso, vedo che la parte di inizializzazione del provider per la Drl è commentato, e che alla riga in cui istanzi il servizio `DgcReaderService` viene passato solo rulesValidator come provider per la blacklist.
Essendo necessario l'utilizzo di entrambi i provider, dovresti utilizzare l'overload di Create che accetta n servizi:

 ``` csharp
private async Task VerGreenPass(string code)    // Aggiunta async Task
{
	ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;
	var httpClient = new HttpClient();

	// Opzioni omesse per brevità
	var trustListProvider = ItalianTrustListProvider.Create(httpClient);
	var rulesValidator = DgcItalianRulesValidator.Create(httpClient);
	var drlBlacklistProvider = ItalianDrlBlacklistProvider.Create(httpClient);

	// Utilizza il secondo overload di Create, che accetta n servizi per ciascun tipo
	var dgcReader = DgcReaderService.Create(
		trustListProviders: new[] { trustListProvider },
		blackListProviders: new IBlacklistProvider[] { rulesValidator, drlBlacklistProvider }, // Vanno registrati entrambi i servizi per la verifica della blacklist
		rulesValidators: new[] { rulesValidator },
		null);


	var result = await dgcReader.GetValidationResult(code, "IT");   // Aggiunta di await per attendere l'esecuzione del task
}
```

**Comment by sfracell** [comment]
Grazie per la veloce risposta,
ho utilizzato task asincrono e registrando entrambi i servizi ottengo dgcValidationResult Status: NeedRulesVerification.

**Comment by DevTrevi** [comment]
Potresti verificare i dettagli del risultato e postarli? In particolare i valori specifici della validazione italiana delle regole?
Puoi accedere al tipo specifico chiamando il metodo
``` csharp
var italianResult = result.RulesValidation.AsItalianValidationResult();
```
Potresti eventualmente indicarmi anche i dati del greenpass, esclusi i dati sensibili della persona?
Se vuoi puoi anche allegare un piccolo programma di esempio che riproduce il problema

**Comment by sfracell** [comment]
il result è un Task<DgcReader.Models.DgcValidationResult> e non contiene una definizione per RulesValidation.
Credo che il problema riguardi anche l'applicazione Verifica c-19 ufficiale. Ieri effettuando le prove su alcuni GreenPass revocati risultavano non validi, oggi invece anche con Verifica c-19  risultano validi come per il tuo SDK, ulteriore controprova è data dalla verifica del gp fasullo di adolf hitler che gira su internet ed effettivamente risulta blacklisted, comunque effettuando delle prove, utilizzando;
 blackListProviders: new IBlacklistProvider[] { rulesValidator, drlBlacklistProvider }
ottengo per tutti i gp verificati lo status NeedRulesVerification.
nel caso utilizzo:
blackListProviders: new IBlacklistProvider[] { rulesValidator, rulesValidator}
allora mi riporta status Valid per tutti tranne che per adolf hitler.

Effettuando lo sniffing delle chiamate effettuate a get.dgc.gov.it, risultano consistenti nel caso in cui effettuo un chiamata eseguendo il metodo  trustListProvider.RefreshTrustList()
non effettua alcuna chiamata nel caso di blacklistProvider.RefreshBlacklist() va in errore.
e nel caso eseguo rulesValidator.RefreshRules() ottengo le regole ed una blacklist molto piccola, in allegato il json della risposta
[Json.txt](https://github.com/DevTrevi/DgcReader/files/7841032/Json.txt)
Grazie.

**Comment by DevTrevi** [comment]
In che senso non contiene una definizione per RulesValidation? E' null?
Mi sembra di capire che ottieni egli errori anche durante le chiamate a RefreshTrustList e RefreshBlacklist, ho capito bene?
Se puoi allegare una piccola console application di esempio potrei verificare se ci sono errori nell'utilizzo della libreria.

E' comunque possibile che alcuni certificati non validi nei giorni scorsi siano tornati validi, qualche giorno fa erano presenti nella Drl circa 400k id, oggi ce ne sono meno di 200k.
Riguardo il greenpass di Hitler, dovrebbe essere incluso nella blacklist di rulesValidator, quella presente nel file json che hai allegato

**Comment by sfracell** [comment]
ok grazie ho ricreato ex novo un progetto console net6 e funziona tutto correttamente, in effetti mi aveva portato fuori strada il fatto che verifica c19 portava i certificati non validi mentre con tuo sdk erano validi.
Comunque in allegato progetto console 
Grazie mille e buon lavoro
[GreenPass.zip](https://github.com/DevTrevi/DgcReader/files/7842233/GreenPass.zip)

**Comment by energywave** [comment]
Confermo che con la sintassi espressa nel readme principale i green pass di Adolf Hitler, Bettino Craxi & co vengono validati correttamente. Con la sintassi in questo issue, ovvero includendo nell'elenco dei blacklist provider anche il RulesProvider ho verificato ed i certificati falsi (che contengono nelle rules italiane la revoca) vengono correttamente identificati come Revoked.
Secondo me quindi è solo necessario aggiornare il readme indicando come istanziare correttamente il DgcReaderService così che i controlli italiani avvengano correttamente.
Grazie mille per lo splendido lavoro!

**Comment by DevTrevi** [comment]
> ok grazie ho ricreato ex novo un progetto console net6 e funziona tutto correttamente, in effetti mi aveva portato fuori strada il fatto che verifica c19 portava i certificati non validi mentre con tuo sdk erano validi. Comunque in allegato progetto console Grazie mille e buon lavoro [GreenPass.zip](https://github.com/DevTrevi/DgcReader/files/7842233/GreenPass.zip)

Ciao @sfracell , ho guardato la tua applicazione, per usare correttamente async/await e il task risultante, dovresti modificare queste righe da così:
``` csharp
var result = dgcReader.GetValidationResult(code, "IT");

if (result.Exception == null)
    rispo = string.Format("{0} - {1} {3}: {2}", result.Result.Dgc.Name.GivenName, result.Result.Dgc.Name.FamilyName, result.Result.StatusMessage.ToString().ToUpper(), Convert.ToDateTime(result.Result.Dgc.DateOfBirth).ToShortDateString());
else
    rispo = result.Exception.Message.ToString();
```
a così
``` csharp
try
{
    var result = await dgcReader.GetValidationResult(code, "IT");
    rispo = string.Format("{0} - {1} {3}: {2}", result.Dgc.Name.GivenName, result.Dgc.Name.FamilyName, result.StatusMessage.ToUpper(), Convert.ToDateTime(result.Dgc.DateOfBirth).ToShortDateString());
}
catch (Exception ex)
{
    rispo = ex.Message.ToString();
}
```

**Comment by DevTrevi** [comment]
Ciao @energywave e @sfracell ,

ho aggiornato la documentazione e aggiunto un nuovo readme specifico per la configurazione dei servizi richiesti per le validazioni italiane, [lo trovate qui](https://github.com/DevTrevi/DgcReader/blob/master/ItalianConfiguration.md)

Spero possa essere di aiuto :)

**Comment by energywave** [comment]
Ottimo lavoro Davide! Hai anche inserito delle info su Dependency Injection che è un argomento che mi manca (vengo dal framework...), proverò a capirlo e usarlo...
Credo che quella pagina aiuterà i nostri connazionali a partire senza esitazioni, bravo!

**Comment by sfracell** [comment]
Ciao @DevTrevi
Grazie mille!
