### ISSUE TITLE
Booster Vaccination with 2/1 doses gives wrong result

### ISSUE THREAD

**Issue by mircoianese** [DevTrevi/DgcReader#44]
There is a problem in the `ValidationMode.Booster`, where it's required to have at least 3 doses for the vaccination to be considered "Booster". 
I had COVID followed by 1 dose of Pfizer. Now I have done the "Booster" dose with Moderna, so my Booster Green Pass has 2 / 1 Doses. This is correctly validated as a Booster in the official App.

Here's the wrong fregment of code in `DgcItalianRulesValidator.cs`: 
```
// Complete cycle
if (validationMode == ValidationMode.Booster)
{
    // Min num of doses to be considered "booster":
    // J&J: required full cycle with at least 2 doses, other vaccines 3 doses
    var boostedDoseNumber = vaccination.MedicinalProduct == VaccineProducts.JeJVacineCode ? 2 : 3;

    // If less thant the minimum "booster" doses, requires a test
    if (vaccination.DoseNumber < boostedDoseNumber)
        result.ItalianStatus = DgcItalianResultStatus.TestNeeded;
    else
        result.ItalianStatus = DgcItalianResultStatus.Valid;
}
```

The official SDK has an additional check where if the number of doses is > than the total number of doses, then the test is not needed.

If possible, can I have an ETA for the next release with this fix?
Thanks a lot

**Comment by DevTrevi** [comment]
Hi @mircoianese , thank you for reporting this bug. I will fix it by this evening
