### ISSUE TITLE
Issue dopo che eseguo la validazione con Verify [Migrato alla nuova versione]

### ISSUE THREAD

**Issue by Elius94** [DevTrevi/DgcReader#47]
"Non è stato possibile caricare il file o l'assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=3.1.22.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' o una delle relative dipendenze. Impossibile trovare il file specificato."

Ciao, questo è e.message del seguente codice:

```c#
try {
    string acceptanceCountry = "IT";    // Specify the 2-letter ISO code of the acceptance country

    // Decode and validate the qr code data.
    // The result will contain all the details of the validated object
    var result = await dgc.Verify(decodedQrcode.ToString(), acceptanceCountry);


    return result;
} catch (Exception e) {
    Console.WriteLine($"Error verifying DGC: {e.Message}");
}
 ```

Il tutto è configurato come segue:

 ```c#

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
var httpClient = new HttpClient();

// You can use the constructor
var rulesValidator = DgcItalianRulesValidator.Create(httpClient,
    new DgcItalianRulesValidatorOptions
    {
        RefreshInterval = TimeSpan.FromHours(24),
        MinRefreshInterval = TimeSpan.FromHours(1),
        BasePath = args[0],
        UseAvailableValuesWhileRefreshing = true
    });

var trustListProvider = ItalianTrustListProvider.Create(httpClient,
    new ItalianTrustListProviderOptions
    {
        RefreshInterval = TimeSpan.FromHours(24),
        MinRefreshInterval = TimeSpan.FromHours(1),
        BasePath = args[0],
        SaveCertificate = true
    });

var drlBlacklistProvider = ItalianDrlBlacklistProvider.Create(httpClient);

// Create an instance of the DgcReaderService
var dgcReader = DgcReaderService.Create(
    trustListProviders: new[] { trustListProvider },
    blackListProviders: new IBlacklistProvider[] { rulesValidator, drlBlacklistProvider },
    rulesValidators: new[] { rulesValidator }
);

 ```

Non capisco se c'è qualcosa di sbagliato nell'utilizzo,
inoltre non ho ben capito dal readme del progetto se devo ancora utilizzare VerifyForItaly o se devo utilizzare gli altri metodi.

Inoltre, col metodo che descrivi nel readme, non capisco dove utilizzare il metodo booster o super green pass,

Grazie mille e scusa il disturbo

**Comment by DevTrevi** [comment]
Ciao @Elius94 , mi potresti dire che tipo di progetto è e quale versione del framework stai usando come target? E' un progetto "legacy" (con file packages.config) oppure è un csproj di tipo nuovo (sdk)?

Riguardo il metodo VerifyForItaly, è equivalente al metodo Verify, con la differenza che seleziona sempre "IT" come paese di verifica e ti permette di specificare su ciascuna chiamata la modalità di valdazione (3G, 2G, Booster) invece che in configurazione.
Se il tuo progetto prevede che tutte le validazioni vengano fatte con la stessa modalità, puoi usare il metodo generico Validate passando "IT" come paese, e selezionando in configurazione la modalità:
``` csharp
var rulesValidator = DgcItalianRulesValidator.Create(httpClient, new DgcItalianRulesValidatorOptions
{
    ValidationMode = ValidationMode.Booster
});

//...

var result = await dgcReader.Verify(data, "IT"); // Questo utilizzerà la modalità specificata in configurazione, o 3G se non specificata
```

Altrimenti, se la selezione della modalità è variabile, ti consiglio di utilizzare il metodo VerifyForItaly:
``` csharp
// Questo metodo consente di specificare la modalità per singola chiamata, a prescindere dal valore configurato
var result = await dcgReader.VerifyForItaly(data, ValidationMode.Booster); 
```

**Comment by Elius94** [comment]
version="v4.0" sku=".NETFramework,Version=v4.7.2"

ciao, questa è la versione di .NET che devo utilizzare... purtroppo non posso passare a versioni successive!
C'è il packages.config.

Grazie mille

**Comment by Elius94** [comment]
Buongiorno, ho eseguito l'aggiornamento dei pacchetti nuget della tua libreria. Purtroppo confermo che dopo aver eseguito il metodo Verify, o anche VerifyForItaly, genera un eccezione il cui e.message è il seguente:

```sh
Error verifying DGC: Non è stato possibile caricare il file o l'assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=3.1.22.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' o una delle relative dipendenze. Impossibile trovare il file specificato.
```

Grazie mille per il supporto.

**Comment by DevTrevi** [comment]
Ciao @Elius94 , ho fatto una prova e l'errore sembra causato dalla dipendenza a EF Core 3.1 con target .NET Framework, utilizzato da `ItalianDrlBlacklistProvider`
Aggiungendo manualmente il pacchetto nuget `Microsoft.Extensions.Configuration.Abstractions` sono riuscito ad eseguirlo correttamente, potresti verificare che risolva il problema?

**Comment by Elius94** [comment]
Ciao @DevTrevi grazie, ora effettivamente non genera quell'eccezione. Tuttavia il risultato della validazione eseguito con il mio GP personale (3 dosi) restituisce "Certificate is not valid"

Qui è come configuro il validatore:
```c#
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
var httpClient = new HttpClient();

// You can use the constructor
var rulesValidator = DgcItalianRulesValidator.Create(httpClient,
    new DgcItalianRulesValidatorOptions
    {
        RefreshInterval = TimeSpan.FromHours(24),
        MinRefreshInterval = TimeSpan.FromHours(1),
        BasePath = args[0],
        UseAvailableValuesWhileRefreshing = true,
        ValidationMode = ValidationMode.Basic3G
    });

var trustListProvider = ItalianTrustListProvider.Create(httpClient,
    new ItalianTrustListProviderOptions
    {
        RefreshInterval = TimeSpan.FromHours(24),
        MinRefreshInterval = TimeSpan.FromHours(1),
        BasePath = args[0],
        SaveCertificate = true
    });

var drlBlacklistProvider = ItalianDrlBlacklistProvider.Create(httpClient);

// Create an instance of the DgcReaderService
var dgcReader = DgcReaderService.Create(
    trustListProviders: new[] { trustListProvider },
    blackListProviders: new IBlacklistProvider[] { rulesValidator, drlBlacklistProvider },
    rulesValidators: new[] { rulesValidator }
);
```

Qui invece è il codice eseguito dopo aver ottenuto la stringa del QR:
```c#
try
{

    string acceptanceCountry = "IT";    // Specify the 2-letter ISO code of the acceptance country

    // Decode and validate the qr code data.
    // The result will contain all the details of the validated object
    var result = await dgc.Verify(decodedQrcode.ToString(), acceptanceCountry);


    return result;
}
catch (Exception e)
{
    Console.WriteLine($"Error verifying DGC: {e.Message}");
}
```

Ora controllo meglio se ho sbagliato qualcosa...

**Comment by Elius94** [comment]
Ok, ho risolto, era colpa del QR code!
Grazie, chiudo
