### ISSUE TITLE
VerifyForItaly not throwing Exception

### ISSUE THREAD

**Issue by FrancescoBonizzi** [DevTrevi/DgcReader#49]
Hi! I just updated my code with the last library version, I initialize all classes like this:

```
_httpClient = new HttpClient();

var dgcReaderServiceLoggerProxy = new GreenPassLoggerProxy<DgcReaderService>(logger);
var rulesValidatorLoggerProxy = new GreenPassLoggerProxy<DgcItalianRulesValidator>(logger);
var trustListProviderLoggerProxy = new GreenPassLoggerProxy<ItalianTrustListProvider>(logger);
var blacklistProviderLoggerProxy = new GreenPassLoggerProxy<ItalianDrlBlacklistProvider>(logger);

var trustListProvider = new ItalianTrustListProvider(_httpClient, null, trustListProviderLoggerProxy);
var drlBlacklistProvider = new ItalianDrlBlacklistProvider(_httpClient, null, blacklistProviderLoggerProxy);
var rulesValidator = new DgcItalianRulesValidator(_httpClient, null, rulesValidatorLoggerProxy);

_greenPassReaderService = DgcReaderService.Create(
    trustListProviders: new[] { trustListProvider },
    blackListProviders: new IBlacklistProvider[] { rulesValidator, drlBlacklistProvider },
    rulesValidators: new[] { rulesValidator },
    logger: dgcReaderServiceLoggerProxy);
```

And I invoke the `Verify` method like this (for example):
```
validationResult = await _greenPassReaderService.VerifyForItaly(
    greenPassQRCodeData,
    ValidationMode.Strict2G,
    throwOnError: true);
```

I made in the past some automatic test with some friends Green Passes to test the library, and now I have two tests failing. Those tests are related to already expired Covid molecular tests, which before the update were correctly failing. 

It **seems** that the method `VerifyForItaly` **doesn't throw the exception**, even if `throwOnError` is set to true!

Full logs:

```
Loading trustlist from file
Public key data for NJpCsMLQco4= from country IT found using DgcReader.TrustListProviders.Italy.ItalianTrustListProvider
HCERT signature verification succeeded using certificate NJpCsMLQco4=
Loading rules from file
Test entries are considered not valid when validation mode is Strict2G
Validation failed: Certificate is not valid
```

If you read the last log line, it says that the certificate is not valid, so I was expecting it to throw an Exception, but it doesn't! 
Am I missing something?

Also, this is an output of that specific `ValidationResult`:
![image](https://user-images.githubusercontent.com/11348479/150498342-9b5cf030-2442-4557-995b-85df6917172c.png)

If you need that test Green Pass raw code, I can send you it in private.

Thanks a lot.

**Comment by DevTrevi** [comment]
Hi @FrancescoBonizzi, thank you for reporting this bug, I just tested it and I can confirm that there is an error in VerifyForItaly that causes the throwOnError flag to be ignored.
I will fix it as soon as possible, I'm sorry for the inconvenience

**Comment by FrancescoBonizzi** [comment]
No problem and thanks to you! As a workaround I check the value inside the validation result.
