### ISSUE TITLE
Xamarin.Android Access to the path "/DgcReaderData\Blacklist\Italy" is denied

### ISSUE THREAD

**Issue by andreabonassi** [DevTrevi/DgcReader#51]
Buongiorno,
sto cercando di integrare i pacchetti Nuget per un'app sviluppata con Xamarin.Android.

Il codice che sto provando è questo:

            var httpClient = new HttpClient();
            var trustListProvider = new ItalianTrustListProvider(httpClient);
            var drlBlacklistProvider = new ItalianDrlBlacklistProvider(httpClient);
            var rulesValidator = new DgcItalianRulesValidator(httpClient);

            var dgcReader = DgcReaderService.Create(
                    trustListProviders: new[] { trustListProvider },
                    blackListProviders: new IBlacklistProvider[] { rulesValidator, drlBlacklistProvider },
                    rulesValidators: new[] { rulesValidator });
            
            string qrCodeData = "xxx";
            string acceptanceCountry = "IT";    // Specify the 2-letter ISO code of the acceptance country
            try
            {
                // Decode and validate the signature.
                // If anything fails, an exception is thrown containing the error details
                var result = await dgcReader.Verify(qrCodeData, acceptanceCountry);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error verifying DGC: {e.Message}");
            }

Il sistema va in eccezione con questo messaggio:
`Access to the path \"/DgcReaderData\\Blacklist\\Italy\" is denied.`

Come posso cambiare il path in cui vengono salvate le informazioni?

**Comment by DevTrevi** [comment]
Buonasera @andreabonassi , dovresti configurare per ciascun servizio il percorso base tramite le opzioni (parametro opzionale dopo httpclient)
Es. per blacklist (da ripetere per tutti gli altri):

``` csharp
new ItalianDrlBlacklistProviderOptions { 
    BasePath = Xamarin.Essentials.FileSystem.CacheDirectory 
}
```

Ti segnalo inoltre questa issue che potrebbe esserti utile: #27

**Comment by vlajkoe** [comment]
@DevTrevi 
please use System.IO.Path.Combine(BasePath,"DgcReaderData","Blacklist","Italy") and so on for other providers,  because when I define the BasePath (Xamarin.Essentials.AppDataDirectory), I get the following path: "/data/user/0/com.app.xamarin/files/DgcReaderData\RuleValidators\Italy/" where "DgcReaderData\RuleValidators\Italy" is the folder name.

**Comment by DevTrevi** [comment]
Thank you for the suggestion @vlajkoe , I will fix it in the next release

**Comment by andreabonassi** [comment]
Posso chiederti se hai già un'idea di quando potrà essere rilasciata la modifica (System.IO.Path.Combine(BasePath,"DgcReaderData","RuleValidators","Italy")) ?
Mi rendo conto che per alcuni path quando chiamo la refresh delle informazioni riscontro un'eccezione:
Win32 IO returned 25. Path: ...

**Comment by DevTrevi** [comment]
@andreabonassi non essendo un bug bloccante pensavo di inserirlo insieme alle prossime modifiche, presumibilmente nel giro di una o due settimane... Anche se il percorso viene composto in parte con backslash e in parte no, dovrebbe funzionare comunque.
Se utilizzi come percorso base una delle cartelle `Xamarin.Essentials.FileSystem.CacheDirectory` o `Xamarin.Essentials.FileSystem.AppDataDirectory` dovresti comunque essere in grado di salvare i file, oppure hai una situazione dove questo non è possibile?

**Comment by andreabonassi** [comment]
Riesco a far funzionare il sistema solo se scrivo in /data/ come BasePath. In tutti gli altri casi riscontro l'eccezione "Win32 IO returned 25".
Dovendo però rilasciare in produzione l'implementazione preferivo avere la versione con la modifica.

**Comment by andreabonassi** [comment]
Sostanzialmente il sistema funziona solo se scrivo in partizioni formattate in fat32 , nelle partizioni ext4 va in eccezione.

**Comment by andreabonassi** [comment]
Ho fatto ulteriori prove e vedo che se scrivo in una partizione ext4 il sistema funziona, pur avendo nel nome della directory i caratteri \\ . Se scrivo invece in una partizione vfat si genera l'eccezione che ti ho riportato sopra.

**Comment by DevTrevi** [comment]
Capisco, purtroppo mi sono limitato a dei test su un emulatore android, quindi non ho riscontrato questo problema. Cercherò di anticipare la prossima release nel fine settimana, per inizio della prossima settimana dovrei riuscire a rilasciare la correzione

**Comment by DevTrevi** [comment]
Hi @vlajkoe  and @andreabonassi , I just released a new version with the suggested fix (Path.Combine), let me know if everiything is ok :)

**Comment by andreabonassi** [comment]
Buongiorno, io ho testato la nuova versione e per quanto riguarda il problema dei path funziona correttamente. Ti ringrazio.
