### ISSUE TITLE
DgcRulesValidationException during Booster Validation in 2.2.1 for Super Green Pass

### ISSUE THREAD

**Issue by mircoianese** [DevTrevi/DgcReader#62]
Hello,

as always thank you for your work.
I've updated to version 2.2.1, and now I'm having an issue (which was not present in 2.2.0) where the validation of a Super-Green Pass in "Booster" mode throws a DgcRulesValidationException with "Certificate is not valid". 

This is my code:

```
var res = await reader.VerifyForItaly(qrTxt, ValidationMode.Booster); // the exception is thrown here
result.IsValid = res.Status is DgcResultStatus.Valid;
// True if an additional test is needed to confirm the Boost
result.TestNeeded = res.GetItalianResultStatus() == DgcItalianResultStatus.TestNeeded;
```

In 2.2.0 the exception was not thrown, and the "result.TestNeeded" variable was set to true.

Here's the stack trace:

```
   at DgcReader.DgcReaderService.<Verify>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DgcReader.ItalianValidationResultsExtensions.<VerifyForItaly>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

.NET Framework 4.5.2

For now I'm reverting back to 2.2.0.
Thank you

**Comment by DevTrevi** [comment]
Hi @mircoianese, thank you, this is by design and there was a bug in v2.2.0 causing the exception not to be thrown when using `VerifyForItaly`, see this issue: #49 
Every result different from Valid will throw an exception (except when no rule validators are registered)

Based on your usage, you can always get the result instead of having exceptions by specifying throwOnError: false
``` csharp
var res = await reader.VerifyForItaly(qrTxt, ValidationMode.Booster, false); // this will not throw exceptions anymore
```

**Comment by mircoianese** [comment]
Hi,

thank you a lot, I confirm that the `throwOnError` option set to `false` is what I was looking for on my use-case.
