### ISSUE TITLE
Validazione vaccinazione

### ISSUE THREAD

**Issue by manuel-esselink** [DevTrevi/DgcReader#68]
Buongiorno,
mi è capitato un caso in cui la libreria in fase di validazione restituisce NotValid, mentre l'app C19 restituisce valido.
Il caso è una seconda dose di vaccino il cui ultimo giorno valido è oggi (oggi è esattamente il 180esimo giorno dopo la somministrazione).

Il problema credo sia dovuto a questo confronto all'interno del file DgcItalianRulesValidator:

```
if (result.ValidUntil < result.ValidationInstant)
                    result.ItalianStatus = DgcItalianResultStatus.NotValid;
```

Dato che ValidUntil contiene solo la data (l'ora è 00:00:00), mentre ValidationInstant contiene data e anche ora attuale, in questo caso restiuisce NotValid.

Guardando invece il codice dell'sdk ufficiale, se ho trovato il punto corretto, il controllo viene fatto solo con le date.
Questo il codice all'interno del file VerificationViewModel.kt:

```
            val startDate: LocalDate =
                LocalDate.parse(clearExtraTime(it.last().certificateValidFrom))

            val endDate: LocalDate =
                LocalDate.parse(clearExtraTime(it.last().certificateValidUntil))

            Log.d("dates", "start:$startDate end: $endDate")
            return when {
                startDate.plusDays(
                    Integer.parseInt(recoveryCertStartDay)
                        .toLong()
                ).isAfter(LocalDate.now()) -> CertificateStatus.NOT_VALID_YET
                LocalDate.now()
                    .isAfter(
                        startDate.plusDays(
                            Integer.parseInt(recoveryCertEndDay)
                                .toLong()
                        )
                    ) -> CertificateStatus.NOT_VALID
                else -> return if (scanMode == ScanMode.BOOSTER) CertificateStatus.TEST_NEEDED else CertificateStatus.VALID
            }
```

Non andrebbe fatto anche nella libreria il confronto solo tra date (solo per la verifica delle vaccinazioni, mentre per i tamponi è importante anche l'ora)?
Grazie per la risposta e per l'ottimo lavoro fatto.

**Comment by DevTrevi** [comment]
Buonasera @manuel-esselink, hai ragione, purtroppo ho dato per scontato che `LocalDate.now()` in kotlin ritornasse data e ora, mentre invece ritorna solo la data.
Inserirò la correzione nel prossimo rilascio, grazie!

**Comment by manuel-esselink** [comment]
Ottimo, grazie a te!
