### ISSUE TITLE
Nuove "medical rules"

### ISSUE THREAD

**Issue by bortolin** [DevTrevi/DgcReader#69]
A vedere questo commit:
https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/commit/2f76ac4147a5f3695ef0c2bb5b89e4a83cebcf69

sembra ci siano nuove regole da gestire, non ho trovato però documentazione in merito.

**Comment by DevTrevi** [comment]
Ho visto anche io, sono nuove regole implementate nella versione 1.1.3: 
https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/compare/1.1.2...1.1.3

Le inserirò nel prossimo rilascio, spero insieme alle modalità WORK/SCHOOL
