### ISSUE TITLE
Italian Work mode

### ISSUE THREAD

**Issue by DevTrevi** [DevTrevi/DgcReader#72]
NOTE: this mode is not yet released and may change before February 15th

For reference:
https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/compare/develop...feature/work-scan-mode

**Comment by andrekiba** [comment]
ciao @DevTrevi, I know that the official WORK mode is not yet released but, to have a chance to update our app before February 15, do you plan to release the v2.5.0 before the week-end? I see all the necessary code is already present in the work-mode branch. I understand that something may change before next Tuesday but at this point I think it is very unlikely, no? Thank you for your effort!

**Comment by DevTrevi** [comment]
Hi @andrekiba , I have published a pre-release version (2.5.0-rc2) of the package, you can download it from nuget by enabling the prerelease version check in Visual Studio.
Unfortunately the official SDK is not yet released and I can not publish a final version including the Work mode...

**Comment by andrekiba** [comment]
Thanks @DevTrevi in the meantime we test with it

**Comment by andrekiba** [comment]
ciao @DevTrevi, do you know if somewhere there are some test certificates to test the work mode? [Here](https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/IT) they are too old.

**Comment by DevTrevi** [comment]
Ciao @andrekiba , as far as I know, unfortunately there aren't updated test certificates, or specific certificates for testing the new validation modes... There are some test data [here](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/tree/develop/sdk/src/test/assets) but these are not full certificates

**Comment by andrekiba** [comment]
ciao @DevTrevi do you think that something else changes before tomorrow? I see you opened some new issues few hours ago.

**Comment by DevTrevi** [comment]
Hi @andrekiba , unfortunately I just saw this morning that an additional branch was set to be integrated in the final 1.1.5 version of the official SDK, I'm just working on it to implement the latest changes...
I have opened one issue for each point listed in [this](https://github.com/ministero-salute/it-dgc-documentation/issues/10#issuecomment-1038630599) reply
I am now implementing [diff between 1.1.4 and entry-into-italy ](https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/compare/release/1.1.4...feature/entry-into-italy), hoping that nothing else change before tomorrow...
