### ISSUE TITLE
Rimuovere la modalità scuola

### ISSUE THREAD

**Issue by astagi** [DevTrevi/DgcReader#85]
Rimuovere la modalità scuola secondo il [DECRETO-LEGGE 4 febbraio 2022, n. 5](https://www.gazzettaufficiale.it/eli/id/2022/02/04/22G00014/sg)

```
La condizione sanitaria che consente la didattica in presenza di
cui al comma 1, lettera b), numero 2, primo periodo,  e  lettera  c),
numero 2), primo periodo, puo' essere controllata  dalle  istituzioni
scolastiche mediante l'applicazione  mobile  per  la  verifica  delle
certificazioni verdi COVID-19 di cui al decreto  del  Presidente  del
Consiglio dei ministri adottato ai sensi dell'articolo 9,  comma  10,
del  decreto-legge  22  aprile   2021,   n.   52,   convertito,   con
modificazioni, dalla legge 17  giugno  2021,  n.  87.  L'applicazione
mobile  di  cui  al  primo  periodo  e'  tecnicamente   adeguata   al
conseguimento delle  finalita'  del  presente  comma  e  puo'  essere
impiegata anche nelle more dell'aggiornamento del decreto di  cui  al
primo periodo. 
```

**Comment by DevTrevi** [comment]
Ciao @astagi , la rimozione della modalità school è obbligatoria, oppure è semplicemente non necessaria? 
Se ho ben capito il decreto indica che l'app mobile Verifica C19 è adeguata, ma non sembra escludere eventuali altre applicazioni che utilizzino librerie certificate, è corretto?

**Comment by rawmain** [comment]
Ciao @DevTrevi 

> la rimozione della modalità school è obbligatoria, oppure è semplicemente non necessaria? Se ho ben capito il decreto indica che l'app mobile Verifica C19 è adeguata, ma non sembra escludere eventuali altre applicazioni che utilizzino librerie certificate, è corretto?

Inizialmente - in virtù di come erano scritte le disposizioni dell'Art.4 DL n°1/2022 - era ammissibile il supporto dello scanmode SCHOOL in SDK/Lib terze parti autorizzate + app terze parti integranti DGC-SDK Android/Kotlin.

Tale articolo è stato abrogato e sostituito appunto dall'Art.6 DL n°5/2022, che indica invece l'adeguatezza di supporto/utilizzo strumenti di validazione solo per le verifier-app ufficiali VerificaC19 per iOS e Android, senza estensione esplicita a app/soluzioni conformi a DPCM 12/10/2021.

Successivamente alla pubblicazione di tale decreto non sono pervenute diverse disposizioni normative e/o istruzioni operative da parte del Ministero della Salute & GPDP.

Ecco perché è giunta solo ora (e non prima) l'indicazione di disabilitare supporto/utilizzo scanmode SCHOOL in lib e app di terze parti.
