### ISSUE TITLE
Inserire l'apposito header User-agent nelle richieste verso le API

### ISSUE THREAD

**Issue by astagi** [DevTrevi/DgcReader#94]
Inserire all'interno delle richieste verso le API l'apposito header User-Agent nella forma 

```
User-Agent: <sdk>-<sdk-technology>/<sdk-version>
```

È possibile omettere `-<sdk-technology>` se la tecnologia è già specificata nel nome (ad esempio verificac19-sdk-php).

Ad esempio nel caso `verificac19-sdk` per Node.js lo User-Agent sarà

```
User-Agent: verificac19-sdk-node/0.9.3
```

**Comment by DevTrevi** [comment]
Ciao @astagi, nel caso di DgcReader che supporta sia .NET Framework (legacy) che .NET, serve differenziare le due tipologie di runtime su cui sta girando la libreria oppure basta indicare `dotnet`?

**Comment by astagi** [comment]
Ciao @DevTrevi se vuoi differenziare il runtime va bene, anche per il resto scelta personale. In realtà serve solo per tracciare l'utilizzo delle API da parte degli SDK.

**Comment by DevTrevi** [comment]
Ciao @astagi, ho pubblicato un aggiornamento che include l'header richiesto, che potrà avere questi 3 valori a seconda del runtime utilizzato:
`DgcReader-netframework/2.5.3` per tutte le versioni di .NET Framework supportate (da 4.5.2 a 4.8)
`DgcReader-mono/2.5.3` per tutte le versioni di Mono (Xamarin)
`DgcReader-dotnet/2.5.3` per tutti gli altri casi, verosimilmente tutte le versioni di .NET / .NET Core

**Comment by astagi** [comment]
Ciao @DevTrevi perfetto :) direi alla grande! Possiamo chiudere questa issue, grazie 🙌
